trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'mycoolproject'
    scannerMode: 'MSBuild'
    projectKey: 'mycoolproject'
    projectName: 'myproject'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DownloadSecureFile@1
  name: mySecureFile 
  inputs:
    secureFile: 'Dashboard.json'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host $(mySecureFile.secureFilePath)'

- task: dependency-check-build-task@6
  inputs:
    projectName: 'myproject'
    scanPath: '**/*.csproj'
    format: 'HTML'

- task: Gitleaks@2
  inputs:
    scanlocation: '$(Build.SourcesDirectory)'
    configtype: 'predefined'
    predefinedconfigfile: 'GitleaksUdmCombo.toml'
    reportformat: 'sarif'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'projectFiles'
